destination: VS Code debug specs - Chrome Java Script & Type Script
title: VS Code debug specs - Chrome Java Script & Type Script
theme: jekyll-theme-cayman
gems:
  - jekyll-readme-index
readme_index:
  enabled: true
  remove_originals: false
